services:
    un.user_repository:
        class: AuthBundle\Entity\Repository\UserRepository
        factory: [@doctrine.orm.default_entity_manager, getRepository]
        arguments:
          - "AuthBundle:User"

    un.auth.user_provider:
        class: AuthBundle\Service\UserProvider
        arguments:
          - @un.user_repository

    un.user_handler:
        class: AuthBundle\Handler\UserHandler
        arguments:
          - @security.encoder_factory

    un.user_roles_form_type:
        class: AP\Bundle\UserBundle\Form\UserRolesForm
        arguments:
          - %security.role_hierarchy.roles%
        tags:
          - { name: form.type, alias: 'user_roles_form' }
