app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    type:     rest

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /
    type:     rest

fos_oauth_server_token:
    pattern: /token
    defaults:
        { _controller: AuthBundle:Token:token }
    requirements:
        _method: POST