un_Course:
    type: rest
    prefix: /courses
    name_prefix: api_1_
    resource: AppBundle\Controller\CourseController

un_Module:
    type: rest
    prefix: /modules
    name_prefix: api_1_
    resource: AppBundle\Controller\ModuleController
