services:
    un.abstract_handler:
        class: AppBundle\Handler\AbstractHandler
        abstract: true
        calls:
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]
            - [setFormFactory, [@form.factory]]
            - [setTokenStorage, [@security.token_storage]]

    un.course_handler:
        class: AppBundle\Handler\CourseHandler
        parent: un.abstract_handler

